export const wordList = {
    "divide into": "把…分成…(divide)",
    "by the time": "到…为止(time)",
    "make sure": "确保(sure)",
    "have a hard time doing sth.": "做某事有困难(time)",
    "prepare for": "为…做准备(prepare)",
    "make great contributions to": "为…做贡献(contribution)",
    "had better (not) do sth.": "最好(不)做某事(better)",
    "avoid doing sth.": "避免做某事(avoid)",
    "be fond of doing sth.": "喜欢做某事(fond)",
    "in person": "亲自(person)",
    "stay awake": "保持清醒(awake)",
    "make room for": "为…腾出空间(room)",
    "give sb. some advice on": "给某人关于…的建议(advice)",
    "go to bed": "上床睡觉(bed)",
    "remember to do sth.": "记得要做某事(remember)",
    "remember doing sth.": "记得做过某事(remember)",
    "would you like to do sth.": "你愿意做某事吗(would)",
    "be so interested in": "对…如此感兴趣(interested)",
    "improve living standards": "提升生活水平(standard)",
    "take pride in": "以…为傲(pride)",
    "be proud of": "以…为傲(proud)",
    "enjoy doing sth.": "喜欢做某事(enjoy)",
    "make comments on": "就…做评价(comment)",
    "self-introduction": "自我介绍(introduction)",
    "take place": "发生(place)",
    "take the place of": "取代(place)",
    "get rid of": "去除，摆脱(rid)",
    "put into action": "付诸行动，把…付诸实践(action)",
    "put into practice": "付诸行动，把…付诸实践(practice)",
    "attract one's attention": "吸引某人的注意力(attract)",
    "draw one's attention": "吸引某人的注意力(draw)",
    "catch one's attention": "吸引某人的注意力(catch)",
    "pay attention to doing sth.": "注意做某事(attention)",
    "tend to do sth.": "往往会做某事(tend)",
    "achieve one's dream": "实现某人的梦想(achieve)",
    "make one's dream come true": "实现某人的梦想(come)",
    "out of": "出自，缺少，脱离(out)",
    "in addition to doing sth.": "除了做某事之外还有(addition)",
    "at all": "根本，究竟(all)",
    "a lack of": "缺乏(lack->n.)",
    "lacking in": "缺乏(lack->adj.)",
    "be caught in the rain": "淋雨(catch)",
    "much to one's surprise": "令某人非常惊讶的是(much)",
    "different kinds of": "不同种类的(kind)",
    "sing high praise for": "高度赞扬(praise)",
    "play an important role in": "在…中扮演重要角色(role)",
    "play an important part in": "在…方面起重要作用(part)",
    "devote oneself to doing sth.": "投身于做某事(devote)",
    "sb. be devoted to doing sth.": "某人投身于做某事(devoted)",
    "devotion to doing sth.": "对做某事的奉献(devotion)",
};